"""
SQLite Database - Manages persistent conversation memory
Stores session-based chat history for the HR Bot
"""

import sqlite3
import os

# This ensures DB file is created inside the database folder
DB_PATH = os.path.join(os.path.dirname(__file__), "memory.db")


def get_connection() -> sqlite3.Connection:
    """Return a connection to the SQLite database."""
    return sqlite3.connect(DB_PATH)


def init_db():
    """Initialize the SQLite database and create tables if they don't exist."""
    print("Initializing SQLite database...")

    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS conversations (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id  TEXT NOT NULL,
            role        TEXT NOT NULL CHECK(role IN ('user', 'assistant')),
            content     TEXT NOT NULL,
            timestamp   DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    """)

    conn.commit()
    conn.close()

    print("Database initialized successfully.")


def save_message(session_id: str, role: str, content: str):
    """
    Persist a single message turn to the database.

    Args:
        session_id: Unique session ID generated by the frontend
        role: Either 'user' or 'assistant'
        content: The message text
    """
    conn = get_connection()
    conn.execute(
        "INSERT INTO conversations (session_id, role, content) VALUES (?, ?, ?)",
        (session_id, role, content)
    )
    conn.commit()
    conn.close()


def get_history(session_id: str, limit: int = 10) -> list[dict]:
    """
    Retrieve recent conversation history for a session in chronological order.

    Fetches the `limit` most recent rows (newest first via ORDER BY DESC),
    then reverses them so the LLM receives oldest-to-newest context.

    Args:
        session_id: Unique session ID to fetch history for
        limit: Maximum number of messages to retrieve (default: 10)

    Returns:
        List of dicts with 'role' and 'content' keys, in chronological order
    """
    conn = get_connection()
    rows = conn.execute(
        """
        SELECT role, content FROM conversations
        WHERE session_id = ?
        ORDER BY timestamp DESC
        LIMIT ?
        """,
        (session_id, limit)
    ).fetchall()
    conn.close()

    # Reverse so LLM sees messages in chronological (oldest-first) order
    return [{"role": role, "content": content} for role, content in reversed(rows)]